## Shibboleth-Login bei ILIAS

## Fuer Deeplinks aus dem Kursbuchungsportal
#  Weiterleitung auf Shibboleth-Sitzung ohne Unterpfad
#  Sonst werden die Sitzungs-Cookies von ILIAS falsch gesetzt
<LocationMatch "/projects/ilias9/__vhb__/resolver.php">
        RedirectMatch "/projects/ilias9/__vhb__/resolver.php(.*)" "http://localhost/projects/ilias9/__vhb__$1"
</LocationMatch>

## Shibboleth-Sitzung
<LocationMatch "/projects/ilias9/__vhb__">
        # Fehlerseiten mit Infos der vhb
        ErrorDocument 401 ../Customizing/global/plugins/Services/AuthShibboleth/ShibbolethAuthenticationHook/VhbShibAuth/templates/accessDenied.html
        ErrorDocument 403 ../Customizing/global/plugins/Services/AuthShibboleth/ShibbolethAuthenticationHook/VhbShibAuth/templates/accessDenied.html

        # Korrekte Weiterleitung nach dem ILIAS-Login
        RedirectMatch "/projects/ilias9/__vhb__/goto.php(.*)"  "http://localhost/projects/ilias9/goto.php$1"
        RedirectMatch "/projects/ilias9/__vhb__/ilias.php(.*)"  "http://localhost/projects/ilias9/ilias.php$1"
        RedirectMatch "/projects/ilias9/__vhb__/error.php(.*)"  "http://localhost/projects/ilias9/error.php$1"

        # Spezialfall: Weiterleitung zur Kursauswahl, wenn mehrere Kurse passen
        RewriteEngine On
        RewriteCond %{QUERY_STRING} ^target=ilias.php(.*)$
        RewriteRule  .*/goto.php  http://localhost/projects/ilias9/ilias.php%1  [L]
</LocationMatch>

# Muss vor anderen Aliases definiert sein!
Alias /projects/ilias9/__vhb__                  /var/www/projects/ilias9/.env/vhbtest/shib_test.php