## Shibboleth-Login bei ILIAS

## Fuer Deeplinks aus dem Kursbuchungsportal
#  Weiterleitung auf Shibboleth-Sitzung ohne Unterpfad
#  Sonst werden die Sitzungs-Cookies von ILIAS falsch gesetzt
<LocationMatch "/__vhb__/resolver.php">
        RedirectMatch "__vhb__/resolver.php(.*)" "https://ilias10.rx.databay.de/__vhb__$1"
</LocationMatch>

## Shibboleth-Sitzung
<LocationMatch "/__vhb__">
        # Fehlerseiten mit Infos der vhb
        ErrorDocument 401 /Customizing/global/plugins/Services/AuthShibboleth/ShibbolethAuthenticationHook/VhbShibAuth/templates/accessDenied.html
        ErrorDocument 403 /Customizing/global/plugins/Services/AuthShibboleth/ShibbolethAuthenticationHook/VhbShibAuth/templates/accessDenied.html

        # Korrekte Weiterleitung nach dem ILIAS-Login
        RedirectMatch "/__vhb__/goto.php(.*)"  "https://ilias10.rx.databay.de/goto.php$1"
        RedirectMatch "/__vhb__/ilias.php(.*)"  "https://ilias10.rx.databay.de/ilias.php$1"
        RedirectMatch "/__vhb__/error.php(.*)"  "https://ilias10.rx.databay.de/error.php$1"

        # Spezialfall: Weiterleitung zur Kursauswahl, wenn mehrere Kurse passen
        RewriteEngine On
        RewriteCond %{QUERY_STRING} ^target=ilias.php(.*)$
        RewriteRule  .*/goto.php  https://ilias10.rx.databay.de/ilias.php%1  [L]
</LocationMatch>

# Muss vor anderen Aliases definiert sein!
Alias /__vhb__                  /var/www/projects/ilias10/extern/vhbtest/shib_test.php
